FROM node:18-alpine AS build
WORKDIR /app
COPY frontend/package*.json ./
RUN npm install
COPY frontend/ ./
RUN npm run build

FROM nginx:alpine
RUN apk add --no-cache apache2-utils && \
    htpasswd -nb tester1 'StrandsFIS2025!' > /etc/nginx/.htpasswd && \
    htpasswd -nb tester2 'StrandsFIS2025!' >> /etc/nginx/.htpasswd && \
    htpasswd -nb tester3 'StrandsFIS2025!' >> /etc/nginx/.htpasswd && \
    htpasswd -nb tester4 'StrandsFIS2025!' >> /etc/nginx/.htpasswd && \
    htpasswd -nb tester5 'StrandsFIS2025!' >> /etc/nginx/.htpasswd
COPY --from=build /app/dist /usr/share/nginx/html
COPY nginx/nginx.conf /etc/nginx/nginx.conf
COPY nginx/conf.d/default.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
